#!/bin/bash
# Готовые команды для деплоя на Hetzner 46.224.99.147
# Скопируй и выполни на сервере

SERVER_IP="46.224.99.147"

echo "📋 Команды для выполнения на сервере Hetzner:"
echo ""
echo "1️⃣  Подключение к серверу:"
echo "   ssh root@${SERVER_IP}"
echo ""
echo "2️⃣  Установка Docker (если еще не установлен):"
echo "   curl -fsSL https://get.docker.com | sh"
echo ""
echo "3️⃣  Клонирование репозитория:"
echo "   cd /opt"
echo "   git clone https://github.com/dant1k/defi-apy-agent.git"
echo "   cd defi-apy-agent"
echo "   git checkout feature/dashboard-redesign"
echo ""
echo "4️⃣  Настройка .env файла:"
echo "   cp .env.example .env"
echo "   nano .env"
echo ""
echo "   В .env обязательно укажи:"
echo "   NEXT_PUBLIC_API_URL=http://${SERVER_IP}:8000"
echo "   NEXT_PUBLIC_API_BASE_URL=http://${SERVER_IP}:8000"
echo ""
echo "5️⃣  Настройка firewall:"
echo "   ufw allow 3000/tcp"
echo "   ufw allow 8000/tcp"
echo "   ufw allow 22/tcp"
echo "   ufw enable"
echo ""
echo "6️⃣  Запуск деплоя:"
echo "   chmod +x deploy.sh"
echo "   ./deploy.sh"
echo ""
echo "7️⃣  Проверка статуса:"
echo "   docker compose -f docker-compose.prod.yml ps"
echo ""
echo "8️⃣  Просмотр логов:"
echo "   docker compose -f docker-compose.prod.yml logs -f"
echo ""
echo "🌐 После деплоя:"
echo "   Frontend: http://${SERVER_IP}:3000"
echo "   API:      http://${SERVER_IP}:8000"
echo "   API Docs: http://${SERVER_IP}:8000/docs"

