name: Codex Auto Task Runner

on:
  issues:
    types: [opened, edited, reopened]
  pull_request:
    types: [closed]

jobs:
  trigger_codex:
    runs-on: ubuntu-latest

    steps:
      - name: Send issue to Codex
        if: github.event_name == 'issues'
        run: |
          curl -X POST https://api.codex.local/trigger             -H "Content-Type: application/json"             -d '{
              "repo": "${{ github.repository }}",
              "issue": "${{ github.event.issue.number }}",
              "action": "${{ github.event.action }}",
              "url": "${{ github.event.issue.html_url }}"
            }'

      - name: Notify Codex of merged PR
        if: github.event_name == 'pull_request' && github.event.pull_request.merged == true
        run: |
          curl -X POST https://api.codex.local/trigger             -H "Content-Type: application/json"             -d '{
              "repo": "${{ github.repository }}",
              "pr": "${{ github.event.pull_request.number }}",
              "merged": true
            }'
